---
  - name: Register with Red Hat Subscription Manager
    redhat_subscription:
      state: present
      username: "{{ rhn_user }}"
      password: "{{ rhn_pass }}"
      pool_ids:
        - "{{ rhn_pool }}"

  - name: Disable all repos
    command: subscription-manager repos --disable "*"

  - name: Enable necessary repos
    command: subscription-manager repos --enable="rhel-7-server-rpms"     --enable="rhel-7-server-extras-rpms"     --enable="rhel-7-server-ose-3.9-rpms"     --enable="rhel-7-fast-datapath-rpms" --enable="rhel-7-server-ansible-2.4-rpms"

  - name: Install necessary packages
    yum:  
      name: '{{ item }}'
      state: present
    with_items: 
    - wget 
    - git 
    - net-tools 
    - bind-utils 
    - iptables-services 
    - bridge-utils 
    - bash-completion 
    - kexec-tools 
    - sos 
    - psacct
    - atomic-openshift-utils
    - docker-1.13.1
    - ipa-client
    - httpd-tools

  - name: configure IPA client
    command: ipa-client-install --server='{{ ipa_server }}' --domain='{{ domain }}' --hostname='{{ ansible_hostname }}'.'{{ domain }}' --principal='{{ ipa_user }}' --password='{{ ipa_password }}' --enable-dns-updates --unattended --force-join

  - name: configure docker storage
    template:
      src: docker-storage-setup.j2
      dest: /etc/sysconfig/docker-storage-setup
      owner: root
      group: root
      mode: 0644

  - name: run docker storage setup
    command: docker-storage-setup

  - name: start and enable Docker
    service:
      name: docker
      state: started
      enabled: true

  - name: Copy hoststemplate file
    template:
      src: hosts.j2
      dest: /etc/ansible/hosts
      owner: root
      group: root
      mode: 0644
    when: "'master' in group_names"

  - name: create ssh key on root account
    shell: 'ssh-keygen -b 2048 -t rsa -f {{ ansible_user_dir }}/.ssh/id_rsa -q -N ""'
    when: "'master' in group_names" 

  - name: capture master public key
    shell: "cat {{ ansible_user_dir }}/.ssh/id_rsa.pub" 
    when: "'master' in group_names"
    register: pubkey

#  - debug: 
#      var: pubkey.stdout_lines

  - name: set the pubkey fact on the master
    set_fact:
      masterpubkey: "{{ pubkey.stdout }}"
    when: "'master' in group_names"

  - name: restart dbus
    service:
      name: dbus
      state: restarted
 
  - name: Set domain in resolve search list
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^search'
      line: 'search {{ domain }}'
      owner: root
      group: root
      mode: 0644

  - name: add key to authorized keys
    authorized_key: 
      user: "{{ ssh_user }}"
      state: present
      key: "{{ hostvars[groups['master'][0]]['masterpubkey']  }}"

  - name: Run prereqs playbook
    command: ansible-playbook  -i /etc/ansible/hosts -e 'host_key_checking=False' /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
    when: "'master' in group_names"
    ignore_errors: True

  - name: Run deploy_cluster playbook
    command: ansible-playbook  -i /etc/ansible/hosts -e 'host_key_checking=False' /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
    when: "'master' in group_names"
    ignore_errors: True

  - name: Configure htpasswd for authentication 
    htpasswd:
      path: '/etc/origin/master/htpasswd'
      name: "{{ ocpuser }}"
      password: "{{ ocppass }}"
    when: "'master' in group_names"

  - name: set htpasswd user up as a cluster-admin
    shell: 'oadm policy add-cluster-role-to-user cluster-admin admin'
    when: "'master' in group_names"

# Play below verified to work - commenting out until ready to integrate into main playbook
#  - name: add DNS Wildcard record pointed to infra node(s)
#    nsupdate:
#      key_name: "{{ dns_keyname }}"
#      key_secret: "{{ dns_key }}"
#      key_algorithm: "{{ dns_algorith }}"
#      server: "{{ dns_server }}"
#      zone: "{{ domain }}"
#      record: "{{ ansible_hostname }}"
#      value: "{{ hostvars[groups['node'][1]]['ansible_default_ipv4']['address'] }}"


