---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    type: master
    master: true
    node: true
    vm_list: 
      - ocpmaster1
  roles:
    - {role: 'ocp-rhv'}

- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars:
    type: node
    master: false
    node: true
    vm_list: "{{ node_list }}"
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'ocp-rhv'}

- hosts: all
  remote_user: root
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'ocp-quick'}
