---
# tasks file for jritenour.vmware-cf-miq
 - name: Generate UUID
   shell: openssl rand -hex 2
   register: uuid_list
 - name: Authenticate to RHV-M
   ovirt_auth:
     url: "https://{{ rhvm_addr }}/ovirt-engine/api"
     username: "{{ rhv_user }}"
     password: "{{ rhv_pass }}" 
     insecure: true

 - name: create the VM
   ovirt_vms: 
     auth: "{{ ovirt_auth }}"
     state: running
     name: "{{ item }}"
     cluster: "{{ cluster }}"
     memory: 16GiB
     cpu_sockets: 2
     wait: True
     template: "{{ template_name }}"
     nics:
       - name: eth0
         profile_name: "{{ network_name }}"
         inferface: virtio
   with_items: "{{ vm_list }}"

 - name: create the DB disk
   ovirt_disks: 
     auth: "{{ ovirt_auth }}"
     name: "{{ item }}-disk2"
     interface: virtio_scsi
     vm_name: "{{ item }}"
     size: "{{ db_size }}GiB"
     format: cow
     storage_domain: "{{ datastore }}" 
   with_items: "{{ vm_list }}"

 - name: List vms
   ovirt_vms_facts:
     fetch_nested: true
     nested_attributes:
       - description
     auth: "{{ ovirt_auth }}"

 - ovirt_nics_facts:
     auth: "{{ ovirt_auth }}"
     vm: "{{ item }}"
     name: eth*
     fetch_nested: true
     nested_attributes:
       - description
   with_items: "{{ vm_list }}" 

 - debug:
     var: ovirt_nics 

 - name: add master server to inventory
   add_host:
     hostname: "{{ ipaddr }}"
     ansible_ssh_user: root
     ansible_ssh_pass: "{{ cf_ssh_pass }}"
     groupname: master
   when: master

 - name: add nodes to inventory
   add_host:
     hostname: "{{ ipaddr }}"
     ansible_ssh_user: root
     ansible_ssh_pass: "{{ cf_ssh_pass }}"
     groupname: node
   when: node
