---
# tasks file for jritenour.vmware-cf-miq
 - name: Authenticate to RHV-M
   ovirt_auth:
     url: "https://{{ rhvm_addr }}/ovirt-engine/api"
     username: "{{ rhv_user }}"
     password: "{{ rhv_pass }}" 
     insecure: true

 - name: create the VM
   ovirt_vms: 
     auth: "{{ ovirt_auth }}"
     state: running
     name: "{{ item }}"
     cluster: "{{ cluster }}"
     memory: 16GiB
     cpu_sockets: 2
     wait: True
     template: "{{ template_name }}"
     nics:
       - name: eth0
         profile_name: "{{ network_name }}"
         inferface: virtio
   with_items: "{{ vm_list }}"

 - name: create the DB disk
   ovirt_disks: 
     auth: "{{ ovirt_auth }}"
     name: "{{ item }}-disk2"
     interface: virtio_scsi
     vm_name: "{{ item }}"
     size: "{{ db_size }}GiB"
     format: cow
     storage_domain: "{{ datastore }}" 
   with_items: "{{ vm_list }}"

 - name: List vms
   ovirt_vms_facts:
     auth: "{{ ovirt_auth }}"
     pattern: name=ocp*
   when: master

 - name: List vms
   ovirt_vms_facts:
     auth: "{{ ovirt_auth }}"
     pattern: name=ocp*
 - debug:
     var: ovirt_vms
   when: node

 - name: Get VM API info
   uri:
     url: "https://{{ rhvm_addr }}{{ item.href }}/reporteddevices"
     method: GET
     return_content: yes
     user: "{{ rhv_user }}"
     password: "{{ rhv_pass }}"
     validate_certs: no
     body_format: raw
     headers:
       Accept: application/json
   with_items: "{{ ovirt_vms }}"
   register: vmapi
    
 - debug:
     var: vmapi.results[0].json

 - name: add master server to inventory
   add_host:
     hostname: "{{ item.json.reported_device[0].ips.ip[0].address }}"
     ansible_ssh_user: root
     ansible_ssh_pass: "{{ cf_ssh_pass }}"
     groupname: master
   with_items: "{{ vmapi.results }}"
   when: master

 - name: add nodes to inventory
   add_host:
     hostname: "{{ item.json.reported_device[0].ips.ip[0].address }}"
     ansible_ssh_user: root
     ansible_ssh_pass: "{{ cf_ssh_pass }}"
     groupname: node
   with_items: "{{ vmapi.results }}"
   when: node
